name: Generate Snake

on:
  schedule:
    # Executar a cada 12 horas
    - cron: "0 */12 * * *"

  # Executar automaticamente a partir da aba Actions
  workflow_dispatch:

  # Também executar a cada push no branch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
          # Definir cores personalizadas
          color_bg: "#0f0f0f"    # Cor de fundo (exemplo: cinza claro)
          color_fg: "#ff0000"    # Cor da cobra (exemplo: cinza escuro)
          color_hb: "#ff4500"    # Cor do alimento (exemplo: laranja avermelhado)

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
