name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia, você pode ajustar conforme necessário
  push:
    branches:
      - main  # ou qualquer branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f dist/snake.svg
          git commit -m 'chore: generate snake animation'
          git push

